key: "investigación/productiva/testing"
export_id: "tpl_investigación_productiva_testing"
name: "investigación/productiva/testing"
version: 1.0.0
storage_version: v0001
modes:
  system:
    jinja2:
      path: "modes/system/jinja2/src"
  user:
    latex:
      path: "modes/user/latex/src"
origins: []
